---
title: "misdi_code_camp_project"
output: html_document
date: "2023-06-22"
---

PACKAGES
```{r}
#installed.packages()
```

```{r}
#install.packages("DT")
library(readr, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(DT, quietly = TRUE)
library(magrittr, quietly = TRUE)
library(tidyr, quietly = TRUE)
```

DATASETS
```{r}
movies_imdb <- read_csv("https://raw.githubusercontent.com/andrewmoles2/rTrainIntroduction/main/r-data-wrangling-1/data/IMDb%20movies.csv")

bechdel <- read_csv("https://raw.githubusercontent.com/andrewmoles2/rTrainIntroduction/main/r-data-wrangling-1/data/raw_bechdel.csv")
```

CLEAN DATA
```{r}
movies_imdb$imdb_title_id <- parse_number(movies_imdb$imdb_title_id)
```

JOIN
```{r}
imdb_bechdel <- inner_join(x = bechdel, y = movies_imdb,
                          by = c("imdb_id" = "imdb_title_id", "year", "title"))
```

WRANGLING
```{r}
global_rating <- imdb_bechdel %>%
  group_by(rating) %>%
  summarise(avg_vote = mean(avg_vote))

global_rating <- global_rating %>%
  mutate(origen = rep("Global", 4), .before = rating)
global_rating

#imdb_bechdel %>% 
#  group_by(country) %>%
#  summarize (Q = n()) %>%
#  arrange(desc(Q))

usa_rating <- imdb_bechdel %>%
  filter(country == "USA") %>%
  group_by(rating) %>%
  summarise(avg_vote = mean(avg_vote))

usa_rating <- usa_rating %>%
  mutate(origen = rep("USA", 4), .before = rating)
usa_rating

uk_rating <- imdb_bechdel %>%
  filter(country == "UK") %>%
  group_by(rating) %>%
  summarise(avg_vote = mean(avg_vote))

uk_rating <- uk_rating %>%
  mutate(origen = rep("UK", 4), .before = rating)
uk_rating

canada_rating <- imdb_bechdel %>%
  filter(country == "Canada") %>%
  group_by(rating) %>%
  summarise(avg_vote = mean(avg_vote))

canada_rating <- canada_rating %>%
  mutate(origen = rep("Canada", 4), .before = rating)
canada_rating

tendencies <- rbind(global_rating, usa_rating, uk_rating, canada_rating)
tendencies
```


VIZ
```{r}
library(ggplot2)
#install.packages("viridis")
#install.packages("hrbrthemes")
library(viridis)
library(hrbrthemes)

top3 <- ggplot(tendencies, aes(x = rating, y = avg_vote, colour = origen)) +
  geom_line() +
  geom_point(shape=15) +
  labs(title = "Top 3 Producing Countries Trends: \n IMDb & bechdel rating", x = "Bechdel Rating", y = "IMDb Ranking", colour = "") +
  theme_ipsum_tw()
  #theme_ipsum_es()
top3

ggsave(filename = "top3.png", top3,
       units = "px", bg = "white")
```

WRANGLING 2
```{r}
year_rating  <- imdb_bechdel %>%
  group_by(year) %>%
  filter(year >= 1950) %>%
  summarise(avg_bechdel = mean(rating))
year_rating

```

VIZ 2

```{r}
evolution <- ggplot(year_rating, aes(x = year, y = avg_bechdel)) +
  geom_smooth(color = "purple", linewidth = 0.5) +
  geom_segment(color = "purple", lty = 4, aes(x = year, xend = year, y = 0, yend = avg_bechdel)) +
  geom_point(size=3, color="purple", fill=alpha("pink", 0.3), alpha=0.7, shape=21, stroke=1) +
    labs(title = "Bechdel rating evolution from 1950", x = "Year", y = "Average Bechdel Rating", colour = "") +
  theme_ipsum_tw()
evolution

ggsave(filename = "evolution.png", evolution,
       units = "px", width = 2500, bg = "white")
```


WRANGLING 3

```{r}
#install.packages("tidyr")
library(tidyr)
country_bechdel <- imdb_bechdel
country_bechdel = separate_rows(country_bechdel,country,sep = ", ")

country_bechdel <- country_bechdel %>%
  group_by(country) %>%
  summarise(avg_bechdel = mean(rating))
country_bechdel


```

VIZ 3
```{r}
#install.packages(c("cowplot", "googleway", "ggrepel", "ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
#install.packages("RColorBrewer")
library(RColorBrewer)

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

world_modified <- left_join(x=world, y = country_bechdel, by = c("name" = "country"))

#glimpse(world_modified)

#world_modified <- world_modified %>%
#  mutate_at("avg_bechdel", ~replace_na(.,-1))

countries <- ggplot(data = world_modified) +
  geom_sf(aes(fill = avg_bechdel)) +
  scale_fill_distiller(palette = "YlGnBu", direction = 1, na.value = "grey90") +
  labs(title = "Bechdel rating per country", fill = "Bechdel rating") +
  theme_ipsum_tw()
countries

ggsave(filename = "countries.png", countries,
       units = "px", width = 2500, bg = "white")

```

